name: EHFSSR_x2_s1
model_type: ImageRestorationModel
scale: 2
num_gpu: 2
manual_seed: 10

datasets:
  train:
    name: Flickr1024-sr-train
    type: PairedStereoImageDataset
    dataroot_gt: datasets/STSR/train/Flickr1024_patches_x2.h5
    dataroot_lq: datasets/STSR/train/Flickr1024_patches_x2.h5
    io_backend:
      type: disk

    gt_size_h: 60
    gt_size_w: 180
    use_hflip: true
    use_vflip: true
    use_rot: false
    flip_RGB: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: Flickr1024-sr-test
    type: PairedImageSRLRDataset
    dataroot_gt: datasets/STSR/test/Flickr1024/HR
    dataroot_lq: datasets/STSR/test/Flickr1024/LR/X2
    io_backend:
      type: disk

# network structures
network_g:
  type: EHFSSR_S
  up_scale: 2
  dim: 48
  groups: 5
  num: 6

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: AdamW
    lr: !!float 1.5e-3
    weight_decay: !!float 0
    betas: [0.9, 0.99]

  scheduler:
    type: TrueCosineAnnealingLR
    T_max: 100000
    eta_min: !!float 1e-7

  total_iter: 100000
  warmup_iter: -1 # no warm up
  mixup: false

  # losses
  pixel_opt:
    type: MSELoss
    loss_weight: 1.
    reduction: mean
  freq_opt:
    type: FFTLoss
    loss_weight: 0.02
    reduction: mean

# validation settings  2e4
val:
  val_freq: !!float 2000
  save_img: false
  trans_num: 1

  max_minibatch: 1

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_skimage_ssim

# logging settings  200 1e4 
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 2000
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
